### ISSUE TITLE
Issue Sequencing Plan

### ISSUE THREAD

**Issue by talllguy** [osmlab/social-paths#1]
Per discussions with OSMUS members on Slack, the following framework provides the desired sequence of addressing the `social_path` issue.

- [x] 1 Update the Wiki
- [x] 1.1 Reach out to tagging list
- [ ] 2 Work with Stamen and team to adjust the CaliParks renderer (the map)
- [ ] 3 Update the OSM data accordingly
- [ ] 3.1 Update other renderers (:construction: To do: come up with top list of renderers to update, e.g. Mapbox, OpenCycleMap, OSM)

cc: @mikelmaron

**Comment by almccon** [comment]
The wiki page is already just about ready: https://wiki.openstreetmap.org/wiki/Proposed_features/Social_path

I will reach out to the tagging list today.

**Comment by almccon** [comment]
Email sent to tagging list: https://lists.openstreetmap.org/pipermail/tagging/2016-March/028966.html

That means we can schedule the start of voting no later than 2 weeks from now. I'm thinking somewhere around April 11.

**Comment by almccon** [comment]
We decided to withdraw the proposal. No further action necessary.
